### PR TITLE
resolves #12 Missing Type Annotations

### LINKED ISSUE #12: Missing Type Annotations
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_tmp007.py:68
- [ ] adafruit_tmp007.py:148
- [ ] adafruit_tmp007.py:152
- [ ] adafruit_tmp007.py:158
- [ ] adafruit_tmp007.py:164
- [ ] adafruit_tmp007.py:170
- [ ] adafruit_tmp007.py:178

### PR DESCRIPTION
**Pull request by tcfranks**

### CODE REVIEW

**Comment by tcfranks** [comment]
TO REVIEWER: class TMP007 - docstring says it returns true (Initialized) or false.  I see no returned type and have indicated by annotating "None".   Am I correct  and docstring needs fixed or did I miss something?  The code raised error for invalid sample rate param or if init fails because device not found.  (Should sample rates be Literal hex values instead of variable names?)

**Comment by FoamyGuy** [comment]
@tcfranks I think you are correct, the current docstring does not accurately describe the functionality. 

If  you're up for it , go ahead and push a new commit to change the docstring. I would lean towards just removing "Returns True if the device is intialized, False otherwise." from the __init__ docstring all together. __init__ doesn't actually return anything, this sentence would be closer to accurate for the __new__ function I think, but in this class we don't have __new__ implemented with our own code so there isn't a great spot to put that information.

Even in the case of __new__  it's not really returning True or False, however the concept of "truthiness" of objects and "falsiness" of None do make it seem functionally similar to returning booleans.

**Comment by FoamyGuy** [comment]
The types in this PR are looking good to me. Thanks for handling another one @tcfranks!

**Comment by tcfranks** [comment]
updated docstring to remove the returns sentence as suggested

**Comment by tekktrik** [comment]
Thanks y'all!

**Pull request merged**
